#!/bin/bash

ARCHIVOCENAM1="GENSYS_ADM_USUARIOS_LDAP_ERROR.csv"
ARCHIVOCENAM2="HUR_ADM_USUARIOS_LDAP_ERROR.csv"
ARCHIVOCENAM3="HRMS_ADM_USUARIOS_LDAP_ERROR.csv"
ARCHIVOCENAM4="ONBOARDING_ADM_USUARIOS_LDAP_EXTERNOS_ERROR.csv"

echo $ARCHIVOCENAM1IN 
cd /home/remedy/NominaTMP/CENAM1
rm $ARCHIVOCENAM1

echo $ARCHIVOCENAM2IN
cd /home/remedy/NominaTMP/CENAM2
rm $ARCHIVOCENAM2

echo $ARCHIVOCENAM3IN
cd /home/remedy/NominaTMP/CENAM3
rm $ARCHIVOCENAM3

echo $ARCHIVOCENAM4IN
cd /home/remedy/NominaTMP/CENAM4
rm $ARCHIVOCENAM4




