#!/bin/bash

#ARCHIVO="GENSYS_ADM_USUARIOS_LDAP.TXT"
#ARCHIVO="HUR_ADM_USUARIOS_LDAP.TXT"
#ARCHIVO="HRMS_ADM_USUARIOS_LDAP.TXT"


cp /home/ldapcenam/CLARO_CENAM_RRHH/HRMS_ADM_USUARIOS_LDAP.TXT /home/remedy/NominaTMP/CENAM3